import type { Metadata } from 'next'
import { Lora, Instrument_Sans } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'
import { Nav } from '@/components/Nav/Navigation'

const lora = Lora({
    variable: '--font-lora',
    subsets: ['latin'],
})

const instrumentSans = Instrument_Sans({
    variable: '--font-instrument-sans',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
})

const orpheusPro = localFont({
    variable: '--font-orpheus-pro',
    src: './fonts/Orpheus-Pro.woff2',
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${lora.variable} ${instrumentSans.variable} ${orpheusPro.variable} antialiased`}
            >
                <Nav />
                {children}
            </body>
        </html>
    )
}
